/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineModel: typeof import('vue')['defineModel']
  const inject: typeof import('vue')['inject']
  const nextTick: typeof import('vue')['nextTick']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onClickOutside: typeof import('@vueuse/core')['onClickOutside']
  const onKeyStroke: typeof import('@vueuse/core')['onKeyStroke']
  const onMounted: typeof import('vue')['onMounted']
  const promiseTimeout: typeof import('@vueuse/core')['promiseTimeout']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const refDebounced: typeof import('@vueuse/core')['refDebounced']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const useAttrs: typeof import('vue')['useAttrs']
  const useElementSize: typeof import('@vueuse/core')['useElementSize']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useFileDialog: typeof import('@vueuse/core')['useFileDialog']
  const useFocus: typeof import('@vueuse/core')['useFocus']
  const useMounted: typeof import('@vueuse/core')['useMounted']
  const useMouseInElement: typeof import('@vueuse/core')['useMouseInElement']
  const useMousePressed: typeof import('@vueuse/core')['useMousePressed']
  const useMutationObserver: typeof import('@vueuse/core')['useMutationObserver']
  const useOffsetPagination: typeof import('@vueuse/core')['useOffsetPagination']
  const useScroll: typeof import('@vueuse/core')['useScroll']
  const useTimeoutFn: typeof import('@vueuse/core')['useTimeoutFn']
  const useWindowSize: typeof import('@vueuse/core')['useWindowSize']
  const watch: typeof import('vue')['watch']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AnchorHTMLAttributes, InputHTMLAttributes, HTMLAttributes, Component } from 'vue'
  import('vue')
}
